import { Achievement } from './types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  // 1 a 46: Conquistas Regulares
  {
    id: 'conhecedor_direitos',
    title: 'Conhecedor dos Direitos',
    subtitle: 'O primeiro passo para uma escola sem zueira pesada',
    description: 'Você concluiu seu primeiro estudo sobre direitos, legislação e medidas de proteção escolar.',
    unlockedDescription: 'Você concluiu seu primeiro estudo sobre direitos, legislação e medidas de proteção escolar.',
    funnyQuote: '‘Zueira que machuca não é brincadeira, é falta de roteiro bom.’',
    funnySticker: '⚖️',
    category: 'detetive',
    tier: 'bronze',
    iconType: 'legal_scales',
    isUnlocked: true,
    xpReward: 30,
    currentProgress: 1,
    maxProgress: 1,
    progressUnit: 'módulo',
    requirementHint: 'Explore o módulo de Legislação Escolar e Direitos.'
  },
  {
    id: 'aliado_escola_segura',
    title: 'Aliado da Escola Segura',
    subtitle: 'Tolerância zero com covardia nos corredores',
    description: 'Você explorou os pilares de prevenção, segurança no ambiente escolar e canais de proteção.',
    unlockedDescription: 'Você explorou os pilares de prevenção, segurança no ambiente escolar e canais de proteção.',
    funnyQuote: '‘Nem o Wi-Fi da escola é tão estável quanto sua determinação em proteger os colegas.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'prata',
    iconType: 'cobalt_shield',
    isUnlocked: true,
    xpReward: 60,
    currentProgress: 3,
    maxProgress: 3,
    progressUnit: 'tópicos',
    requirementHint: 'Conclua os 3 tópicos do programa de segurança escolar.'
  },
  {
    id: 'especialista_em_respeito',
    title: 'Especialista em Respeito',
    subtitle: 'Neurônios brilhando mais que a tela do celular',
    description: 'Você aprendeu como agir com empatia e apoiar colegas como testemunha ativa.',
    unlockedDescription: 'Você aprendeu como agir com empatia e apoiar colegas como testemunha ativa.',
    funnyQuote: '‘QI de empatia acima de 9.000! Uma mente focada na compreensão.’',
    funnySticker: '🧠',
    category: 'empatia',
    tier: 'ouro',
    iconType: 'brain_empathy',
    isUnlocked: true,
    xpReward: 120,
    currentProgress: 5,
    maxProgress: 5,
    progressUnit: 'ações empáticas',
    requirementHint: 'Demonstre empatia e apoio ativo a colegas em 5 situações.'
  },
  {
    id: 'primeiro_passo_sabedoria',
    title: 'Primeiro Passo da Sabedoria',
    subtitle: 'O Início da Grande Jornada',
    description: 'Você iniciou sua jornada respondendo ao seu primeiro quiz educativo.',
    unlockedDescription: 'Concluiu seu primeiro teste de conscientização ética!',
    funnyQuote: '‘O primeiro passo é sempre o mais corajoso.’',
    funnySticker: '🌱',
    category: 'sabedoria',
    tier: 'bronze',
    iconType: 'copper_axe',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz',
    requirementHint: 'Responda ao menos 1 quiz educativo sobre bullying.'
  },
  {
    id: 'detetive_bullying',
    title: 'Perito da Legislação 13.185',
    subtitle: 'Rastreador de Direitos',
    description: 'Analisou artigos da lei de combate à intimidação sistemática com atenção aos detalhes.',
    unlockedDescription: 'Você domina as nuances e garantias legais contra a violência escolar!',
    funnyQuote: '‘Conhecimento da lei é uma lanterna nas sombras.’',
    funnySticker: '🔍',
    category: 'detetive',
    tier: 'bronze',
    iconType: 'cave_binoculars',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo',
    requirementHint: 'Explore o módulo de Legislação e medidas pedagógicas.'
  },
  {
    id: 'respeito_em_acao',
    title: 'Coração da Convivência',
    subtitle: 'Cultura da Não-Violência',
    description: 'Completou a formação sobre convivência ética e empatia ativa.',
    unlockedDescription: 'Dominou os conceitos de respeito mútuo e acolhimento.',
    funnyQuote: '‘Respeito não se impõe, se constrói todos os dias.’',
    funnySticker: '💖',
    category: 'empatia',
    tier: 'bronze',
    iconType: 'life_crystal',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo',
    requirementHint: 'Conclua a Trilha do Respeito & Empatia.'
  },
  {
    id: 'guardiao_digital',
    title: 'Sentinela Cibernético',
    subtitle: 'Vigilância contra o Cyberbullying',
    description: 'Concluiu o estudo sobre segurança, cyberbullying e empatia digital nas redes sociais.',
    unlockedDescription: 'Pronto para identificar e neutralizar o cyberbullying na rede.',
    funnyQuote: '‘A internet precisa de mais sentinelas da paz e menos haters de plantão.’',
    funnySticker: '👁️',
    category: 'escudo',
    tier: 'bronze',
    iconType: 'retinazer_laser',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo',
    requirementHint: 'Estude o tipo Cyberbullying na Matriz de Violência.'
  },
  {
    id: 'mente_tranquila',
    title: 'Primeira Respiração',
    subtitle: 'Calma Interior Restaurada',
    description: 'Completou seu primeiro ciclo de autorregulação emocional 4-7-8.',
    unlockedDescription: 'Aprendeu a desacelerar e respirar antes de tomar decisões.',
    funnyQuote: '‘Inspire paz, expire tranquilidade.’',
    funnySticker: '🕯️',
    category: 'zen',
    tier: 'bronze',
    iconType: 'peace_candle',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'sessão',
    requirementHint: 'Faça 1 ciclo completo de respiração 4-7-8 no Apoio Emocional.'
  },
  {
    id: 'gabarito_de_mestre',
    title: 'Gabaritador Impecável',
    subtitle: 'Precisão Cirúrgica 100%',
    description: 'Alcançou pontuação perfeita (100%) em um quiz educativo da escola.',
    unlockedDescription: 'Acertou todas as questões sobre legislação e convivência!',
    funnyQuote: '‘Gabaritar com ética é a verdadeira nota dez.’',
    funnySticker: '🎯',
    category: 'sabedoria',
    tier: 'prata',
    iconType: 'golden_bullseye',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz 100%',
    requirementHint: 'Acerte 100% das questões do Quiz Educativo.'
  },
  {
    id: 'explorador_de_rotas',
    title: 'Mestre dos Desfechos',
    subtitle: 'Navegador de Casos Reais',
    description: 'Explorou e concluiu 2 simulações e triagens pedagógicas interativas.',
    unlockedDescription: 'Entendeu como a gravidade da situação dita o protocolo correto.',
    funnyQuote: '‘Quem enxerga os caminhos escolhe sempre o da paz.’',
    funnySticker: '🧭',
    category: 'detetive',
    tier: 'prata',
    iconType: 'golden_compass',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 2,
    progressUnit: 'casos',
    requirementHint: 'Explore 2 níveis da Triagem Pedagógica por Semáforo.'
  },
  {
    id: 'mediador_da_paz',
    title: 'Voz da Mediação',
    subtitle: 'Diálogo Ativo e Escuta',
    description: 'Tomou 3 decisões baseadas em diálogo, escuta atenta e reconciliação.',
    unlockedDescription: 'Optou pelo diálogo onde outros escolheriam o atrito.',
    funnyQuote: '‘A mediação desarma a violência sem ferir ninguém.’',
    funnySticker: '🕊️',
    category: 'empatia',
    tier: 'prata',
    iconType: 'hallow_dove',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'decisões',
    requirementHint: 'Tome 3 decisões empáticas na plataforma.'
  },
  {
    id: 'escudo_inabalavel',
    title: 'Escudo Ankh Protetor',
    subtitle: 'Imunidade à Negatividade',
    description: 'Priorizou a proteção e o apoio em 3 dilemas éticos sem vacilar.',
    unlockedDescription: 'Um sentinela sempre coloca a integridade do colega à frente.',
    funnyQuote: '‘Proteger quem precisa é o dever mais nobre.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'prata',
    iconType: 'ankh_shield',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'ações',
    requirementHint: 'Explore canais de denúncia segura e apoios oficiais.'
  },
  {
    id: 'mestre_zen',
    title: 'Mestre do Bonsai Interior',
    subtitle: 'Autorregulação Plena',
    description: 'Realizou 3 sessões de respiração consciente 4-7-8 no jardim da mente.',
    unlockedDescription: 'Mente calma, coração sereno e decisões equilibradas.',
    funnyQuote: '‘A calma é a fortaleza inabalável do sábio.’',
    funnySticker: '🪴',
    category: 'zen',
    tier: 'prata',
    iconType: 'zen_bonsai',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'sessões',
    requirementHint: 'Complete 3 ciclos de respiração no Espaço Zen.'
  },
  {
    id: 'oraculo_do_saber',
    title: 'Oráculo do Conhecimento',
    subtitle: 'Visão Transcendente da Convivência',
    description: 'Completou 3 quizzes educativos com alto aproveitamento e dedicação.',
    unlockedDescription: 'Bagagem teórica sólida sobre prevenção e combate ao bullying!',
    funnyQuote: '‘A sabedoria compartilhada protege a todos ao redor.’',
    funnySticker: '🔮',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'wizard_crystal_ball',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes',
    requirementHint: 'Realize o Quiz Educativo 3 vezes com alto rendimento.'
  },
  {
    id: 'estrategista_escolar',
    title: 'Estrategista da Convivência',
    subtitle: 'Mesa Tática de Prevenção',
    description: 'Completou 4 análises de casos e cenários de convivência com pensamento crítico.',
    unlockedDescription: 'Compreende com precisão os fatores de risco e métodos de proteção.',
    funnyQuote: '‘Prevenir é o melhor lance em qualquer partida.’',
    funnySticker: '♟️',
    category: 'detetive',
    tier: 'ouro',
    iconType: 'chess_war_table',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'análises',
    requirementHint: 'Conclua a triagem completa e explore os 4 D\'s da ação.'
  },
  {
    id: 'farol_da_empatia',
    title: 'Fruta Dourada da Empatia',
    subtitle: 'Acolhimento Nobre',
    description: 'Completou a trilha de respeito e acumulou 5 escolhas de empatia genuína.',
    unlockedDescription: 'Você é um ponto de apoio e acolhimento para os colegas!',
    funnyQuote: '‘Onde há afeto, o preconceito não encontra morada.’',
    funnySticker: '💛',
    category: 'empatia',
    tier: 'ouro',
    iconType: 'life_fruit_gold',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'marcos',
    requirementHint: 'Finalize o Módulo de Respeito e leia as frases de apoio.'
  },
  {
    id: 'bastiao_da_seguranca',
    title: 'Castelo do Paladino',
    subtitle: 'Fortaleza Institucional',
    description: 'Estudou a legislação e acumulou 5 decisões protetivas para a escola.',
    unlockedDescription: 'Conhece as garantias das Leis 13.185/15 e 14.811/24.',
    funnyQuote: '‘Escola segura se constrói com muralhas de solidariedade.’',
    funnySticker: '🏰',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'paladin_castle',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'estudos',
    requirementHint: 'Estude os artigos da lei e conheça os canais 188 e 100.'
  },
  {
    id: 'monge_da_harmonia',
    title: 'Flor de Mana da Harmonia',
    subtitle: 'Serenidade Profunda',
    description: 'Acumulou 5 sessões de respiração e utilizou o apoio emocional nos momentos certos.',
    unlockedDescription: 'Sua serenidade inspira todos os colegas da sala!',
    funnyQuote: '‘A paz que você cultiva transforma o clima da sala inteira.’',
    funnySticker: '🌸',
    category: 'zen',
    tier: 'ouro',
    iconType: 'mana_flower',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'sessões',
    requirementHint: 'Faça 5 sessões de respiração 4-7-8 e ouça as frases.'
  },
  {
    id: 'doutor_da_etica',
    title: 'Doutor em Cidadania Escolar',
    subtitle: 'Pergaminho de Honra',
    description: 'Concluiu todos os quizzes educativos da plataforma com maestria e nota alta.',
    unlockedDescription: 'Nível doutoral em cidadania e direitos humanos escolares!',
    funnyQuote: '‘Diploma de honra ao mérito da convivência fraterna.’',
    funnySticker: '📜',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'scholar_quill',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'quizzes',
    requirementHint: 'Obtenha a nota máxima no Quiz da EEMTI Alfredo Machado.'
  },
  {
    id: 'guardiao_supremo',
    title: 'Lâmina da Terra Sagrada',
    subtitle: 'Defensor da Coletividade',
    description: 'Concluiu Leis, Respeito, Triagem, Quiz e Apoio Emocional em sua totalidade.',
    unlockedDescription: 'Dominou todos os 5 pilares do projeto Sentinela Escolar!',
    funnyQuote: '‘O guardião supremo protege com sabedoria, justiça e acolhimento.’',
    funnySticker: '🗡️',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'terra_blade',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'pilares',
    requirementHint: 'Conclua todas as seções pedagógicas e o quiz.'
  },
  {
    id: 'colecionador_supremo',
    title: 'Baú Dourado de Honrarias',
    subtitle: 'Colecionador Voraz de Troféus',
    description: 'Desbloqueou 15 insígnias diferentes na plataforma.',
    unlockedDescription: 'Sua estante de honrarias escolares está repleta de tesouros éticos!',
    funnyQuote: '‘Cada distintivo conquistado carrega uma lição eterna de cidadania.’',
    funnySticker: '💎',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'golden_chest_gems',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'insígnias',
    requirementHint: 'Desbloqueie 15 conquistas no sistema.'
  },
  {
    id: 'explorador_tipos',
    title: 'Matriz das Oito Gemas',
    subtitle: 'Diagnóstico Preciso de Agressões',
    description: 'Explorou e compreendeu os 8 tipos de bullying na matriz de prevenção.',
    unlockedDescription: 'Sabe diferenciar agressões verbais, físicas, relacionais e digitais com clareza.',
    funnyQuote: '‘Nomear e classificar o problema é o primeiro passo para extingui-lo.’',
    funnySticker: '💠',
    category: 'detetive',
    tier: 'bronze',
    iconType: 'gem_lock_matrix',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'tipos',
    requirementHint: 'Estude todos os 8 tipos na Matriz de Bullying.'
  },
  {
    id: 'maratona_questoes',
    title: 'Botas Aladas do Maratonista',
    subtitle: 'Vinte Questões Respondidas',
    description: 'Respondeu a 20 questões em quizzes educativos com ritmo e determinação.',
    unlockedDescription: 'Dedicação exemplar nos estudos de direitos escolares!',
    funnyQuote: '‘A velocidade na assimilação cria hábitos sólidos para a vida.’',
    funnySticker: '🥾',
    category: 'sabedoria',
    tier: 'prata',
    iconType: 'hermes_boots',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 20,
    progressUnit: 'questões',
    requirementHint: 'Responda a 20 questões de quizzes.'
  },
  {
    id: 'desafio_perfeito',
    title: 'Arco Carmesim da Precisão',
    subtitle: 'Duplo Gabarito Perfeito',
    description: 'Alcançou 100% de aproveitamento em 2 rodadas de quiz sem nenhum erro.',
    unlockedDescription: 'Provou que seu conhecimento é afiado e sem vacilos.',
    funnyQuote: '‘Duas flechas no centro do alvo comprovam o verdadeiro domínio.’',
    funnySticker: '🏹',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'tendon_bow',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 2,
    progressUnit: 'quizzes 100%',
    requirementHint: 'Gabarite 2 rodadas do quiz educativo.'
  },
  {
    id: 'sentinela_zen',
    title: 'Fogueira e Lanterna de Vida',
    subtitle: 'Oito Sessões de Calma',
    description: 'Acumulou 8 sessões de respiração consciente 4-7-8 para manter o foco.',
    unlockedDescription: 'Mente centrada e aquecida pela paz interior.',
    funnyQuote: '‘Uma fogueira de serenidade afasta os monstros da ansiedade.’',
    funnySticker: '🔥',
    category: 'zen',
    tier: 'ouro',
    iconType: 'campfire_heart_lantern',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'sessões',
    requirementHint: 'Acumule 8 sessões de respiração profunda.'
  },
  {
    id: 'multiverso_simulacoes',
    title: 'Poção do Portal Dimensional',
    subtitle: 'Navegador de Todos os Cenários',
    description: 'Concluiu análises dos 3 níveis de semáforo e descobriu todos os desfechos éticos.',
    unlockedDescription: 'Explorou todas as ramificações de prevenção e intervenção segura.',
    funnyQuote: '‘Toda escolha gera reflexos em diferentes realidades da escola.’',
    funnySticker: '🧪',
    category: 'detetive',
    tier: 'lendario',
    iconType: 'wormhole_portal',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'níveis',
    requirementHint: 'Analise todos os níveis da Triagem Pedagógica.'
  },
  {
    id: 'veterano_questoes',
    title: 'Bigorna e Forja do Saber',
    subtitle: 'Quarenta Questões Forjadas',
    description: 'Respondeu a 40 questões em quizzes educativos com firmeza e constância.',
    unlockedDescription: 'Conhecimento forjado a ferro e fogo para defender a escola.',
    funnyQuote: '‘Praticar na forja consolida o caráter ético.’',
    funnySticker: '⚒️',
    category: 'sabedoria',
    tier: 'prata',
    iconType: 'iron_anvil_forge',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 40,
    progressUnit: 'questões',
    requirementHint: 'Responda a 40 questões em quizzes.'
  },
  {
    id: 'oraculo_cinco_estrelas',
    title: 'Constelação das 5 Estrelas Cadentes',
    subtitle: 'Três Gabaritos Perfeitos Consecutivos',
    description: 'Alcançou 100% de aproveitamento em 3 rodadas do quiz pedagógico.',
    unlockedDescription: 'Conhecimento luminoso como uma chuva de estrelas cadentes!',
    funnyQuote: '‘Três notas dez seguidas brilham como uma constelação inteira.’',
    funnySticker: '🌠',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'five_fallen_stars',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes 100%',
    requirementHint: 'Gabarite 3 rodadas do quiz educativo.'
  },
  {
    id: 'explorador_total_matriz',
    title: 'Tomo do Guia da Matriz',
    subtitle: 'Estudo Completo das Agressões',
    description: 'Estudou a fundo a matriz completa de tipos de agressão e sinais de alerta.',
    unlockedDescription: 'Conhece as 8 faces do bullying e suas respectivas formas de prevenção.',
    funnyQuote: '‘Atenção rigorosa aos sinais transforma e salva vidas.’',
    funnySticker: '📖',
    category: 'detetive',
    tier: 'prata',
    iconType: 'guide_crafting_book',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'tipos',
    requirementHint: 'Marque como estudados todos os tipos de violência.'
  },
  {
    id: 'combo_iniciante_sentinela',
    title: 'Bancada do Sentinela Iniciante',
    subtitle: 'Pilares Integrados de Ação',
    description: 'Concluiu Leis, Respeito, 2 Quizzes e 2 Triagens na mesma jornada.',
    unlockedDescription: 'Cidadão completo, ativo e prestativo no ambiente escolar.',
    funnyQuote: '‘Unir teoria, reflexão e atitude transforma o ambiente escolar.’',
    funnySticker: '🪓',
    category: 'escudo',
    tier: 'prata',
    iconType: 'starter_workbench',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'etapas',
    requirementHint: 'Complete Leis + Respeito + 2 Quizzes + 2 Triagens.'
  },
  {
    id: 'empatia_inabalavel',
    title: 'Estátua do Anjo Acolhedor',
    subtitle: 'Oito Decisões Fraternas',
    description: 'Acumulou 8 escolhas de acolhimento e escuta empática na plataforma.',
    unlockedDescription: 'Um coração nobre que pulsa em sintonia com a fraternidade escolar.',
    funnyQuote: '‘A empatia desmorona qualquer muralha de hostilidade.’',
    funnySticker: '👼',
    category: 'empatia',
    tier: 'ouro',
    iconType: 'angel_statue_heart',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'ações',
    requirementHint: 'Acumule 8 decisões e leituras de acolhimento.'
  },
  {
    id: 'mente_inabalavel',
    title: 'Crânio de Obsidiana e Mente Fria',
    subtitle: 'Seis Sessões de Foco Absoluto',
    description: 'Acumulou 6 sessões de respiração profunda 4-7-8 com blindagem emocional.',
    unlockedDescription: 'Imunidade ao calor dos impulsos e domínio sereno das emoções.',
    funnyQuote: '‘Mente de obsidiana não se quebra com provocações baratas.’',
    funnySticker: '💀',
    category: 'zen',
    tier: 'ouro',
    iconType: 'obsidian_skull_calm',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 6,
    progressUnit: 'sessões',
    requirementHint: 'Complete 6 ciclos de respiração consciente.'
  },
  {
    id: 'escudo_de_ouro_decisao',
    title: 'Escudo Solar da Coragem',
    subtitle: 'Oito Escolhas Protetivas',
    description: 'Acumulou 8 decisões de proteção e firmeza contra a injustiça nos corredores.',
    unlockedDescription: 'Sempre firme na defesa de um colégio acolhedor e justo.',
    funnyQuote: '‘Quem se cala consente; quem age com o escudo protege a todos.’',
    funnySticker: '☀️',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'solar_flare_shield',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'escolhas',
    requirementHint: 'Acumule 8 ações de proteção no sistema.'
  },
  {
    id: 'nivel_cinco_guardiao',
    title: 'Brasão Prateado de Nível 5',
    subtitle: 'Patente de Sentinela Experiente',
    description: 'Alcançou o Nível 5 de progressão na plataforma acumulando XP ético.',
    unlockedDescription: 'Reconhecimento oficial de Sentinela Experiente da escola!',
    funnyQuote: '‘Nível 5: um marco de respeito, disciplina e dedicação.’',
    funnySticker: '🥈',
    category: 'escudo',
    tier: 'prata',
    iconType: 'silver_crest_five',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'níveis',
    requirementHint: 'Alcance o Nível 5 de sentinela acumulando XP.'
  },
  {
    id: 'conhecedor_total_quizzes',
    title: 'Megashark Coroado',
    subtitle: 'Cinco Gabaritos Perfeitos',
    description: 'Gabaritou o quiz pedagógico 5 vezes com 100% de acerto consecutivo.',
    unlockedDescription: 'Conhecimento perfeito, veloz e inquestionável!',
    funnyQuote: '‘Disparos de sabedoria na velocidade de um fuzil de elite.’',
    funnySticker: '🦈',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crowned_megashark',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'quizzes 100%',
    requirementHint: 'Gabarite 5 quizzes diferentes com 100%.'
  },
  {
    id: 'arquiteto_do_destino',
    title: 'Blueprint do Engenheiro da Paz',
    subtitle: 'Régua Mecânica de Prevenção',
    description: 'Explorou todos os caminhos, opções e recomendações da triagem por semáforo.',
    unlockedDescription: 'Conhece as alternativas e rotas de mediação para cada grau de risco.',
    funnyQuote: '‘Quem projeta caminhos claros constrói pontes seguras entre as pessoas.’',
    funnySticker: '📐',
    category: 'detetive',
    tier: 'ouro',
    iconType: 'blueprint_ruler',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'caminhos',
    requirementHint: 'Explore todos os níveis do semáforo de triagem.'
  },
  {
    id: 'explorador_segredos_sim',
    title: 'Passagem Secreta da Masmorra',
    subtitle: 'Alavanca Oculta Acionada',
    description: 'Descobriu a camuflagem e recursos secretos de emergência do sistema.',
    unlockedDescription: 'Acionou o modo de segurança discreta com sucesso.',
    funnyQuote: '‘A segurança pedagógica às vezes exige discrição absoluta.’',
    funnySticker: '🗝️',
    category: 'detetive',
    tier: 'ouro',
    iconType: 'secret_dungeon_lever',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'segredo',
    requirementHint: 'Abra a camuflagem de emergência (Mini-game Pac-Man).'
  },
  {
    id: 'missao_cumprida_maratonista',
    title: 'Troféu de Ouro do Maratonista',
    subtitle: 'Sessenta Questões Concluídas',
    description: 'Respondeu a 60 questões de quizzes educativos com alto comprometimento.',
    unlockedDescription: 'Verdadeiro maratonista da cultura de paz e cidadania escolar.',
    funnyQuote: '‘Sua dedicação aos estudos inspira toda a comunidade escolar.’',
    funnySticker: '🏆',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'gold_trophy_laurel',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 60,
    progressUnit: 'questões',
    requirementHint: 'Responda a 60 questões no total.'
  },
  {
    id: 'harmonia_plena',
    title: 'Borboleta Prismática do Arco-Íris',
    subtitle: 'Dez Sessões de Calma Plena',
    description: 'Realizou 10 sessões de respiração e utilizou o apoio emocional com regularidade.',
    unlockedDescription: 'Paz profunda, equilíbrio e aura de harmonia exemplar.',
    funnyQuote: '‘A serenidade colore os dias mais cinzentos com um arco-íris de paz.’',
    funnySticker: '🦋',
    category: 'zen',
    tier: 'ouro',
    iconType: 'prismatic_lacewing',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'sessões',
    requirementHint: 'Realize 10 sessões de respiração 4-7-8.'
  },
  {
    id: 'nivel_dez_comandante',
    title: 'Dragão de Poeira Estelar Nível 10',
    subtitle: 'Comandante da Cultura Escolar',
    description: 'Alcançou o Nível 10 de progressão na plataforma acumulando XP.',
    unlockedDescription: 'Liderança máxima na mediação de conflitos escolares e convivência!',
    funnyQuote: '‘Nível 10: O dragão estelar guia os passos dos novos sentinelas.’',
    funnySticker: '🐉',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'stardust_dragon_ten',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'níveis',
    requirementHint: 'Alcance o Nível 10 na plataforma.'
  },
  {
    id: 'diplomata_da_paz',
    title: 'Aperto de Mão Fraterno',
    subtitle: 'Quinze Ações Empáticas',
    description: 'Concluiu estudos extensivos e acumulou 15 escolhas de empatia e diálogo ativo.',
    unlockedDescription: 'Mestre em diálogo, respeito recíproco e tolerância construtiva.',
    funnyQuote: '‘O verdadeiro diplomata transforma desentendimentos em laços fraternos.’',
    funnySticker: '🤝',
    category: 'empatia',
    tier: 'lendario',
    iconType: 'peace_handshake',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'ações',
    requirementHint: 'Acumule 15 ações e reflexões empáticas.'
  },
  {
    id: 'guardiao_blindado_escola',
    title: 'Carapaça de Besouro Impenetrável',
    subtitle: 'Quinze Ações de Segurança Coletiva',
    description: 'Concluiu módulos de proteção e acumulou 15 escolhas protetivas.',
    unlockedDescription: 'Sua presença traz tranquilidade e segurança firme aos corredores.',
    funnyQuote: '‘Um escudo firme para proteger quem precisa e guiar com paciência.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'beetle_carapace',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'ações',
    requirementHint: 'Acumule 15 escolhas e estudos de proteção.'
  },
  {
    id: 'grande_colecionador',
    title: 'Vitrine do Grande Diamante',
    subtitle: 'Vinte e Cinco Distintivos no Almanaque',
    description: 'Desbloqueou 25 conquistas diferentes na plataforma Sentinela Escolar.',
    unlockedDescription: 'Mais da metade do almanaque conquistado com louvor e brilho!',
    funnyQuote: '‘Colecionar sabedoria é o tesouro mais valioso dos grandes líderes.’',
    funnySticker: '💎',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'diamond_display_case',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 25,
    progressUnit: 'insígnias',
    requirementHint: 'Desbloqueie 25 conquistas no sistema.'
  },
  {
    id: 'nivel_quinze_lorde',
    title: 'Manto Nobre do Lorde 15',
    subtitle: 'Lorde Sentinela Honorário',
    description: 'Alcançou o Nível 15 de progressão na plataforma com dedicação lendária.',
    unlockedDescription: 'Patente nobre de guardião imortal da paz escolar!',
    funnyQuote: '‘Sua postura ética é referência viva para todas as turmas do colégio.’',
    funnySticker: '👑',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'lorde_cloak_fifteen',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'níveis',
    requirementHint: 'Alcance o Nível 15 na plataforma.'
  },
  {
    id: 'mestre_absoluto_sentinela',
    title: 'Zenith Cósmica da Convivência',
    subtitle: 'Mestre Supremo da Cultura de Paz',
    description: 'Alcançou Nível 12+, quiz perfeito, triagem completa, Leis e Respeito.',
    unlockedDescription: 'Excelência em todas as dimensões da convivência cidadã e ética escolar!',
    funnyQuote: '‘Mestre supremo: a paz é o seu legado eterno nos corredores.’',
    funnySticker: '🌌',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'zenith_sword_beam',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'requisitos',
    requirementHint: 'Alcance Nível 12+ e complete todos os módulos teóricos.'
  },
  {
    id: 'lenda_viva_sentinela',
    title: 'Coroa Suprema e Fogo Eterno',
    subtitle: 'Patente Máxima 18+ da EEMTI',
    description: 'Alcançou Nível 18+, 2.500+ XP e 35 conquistas desbloqueadas no almanaque.',
    unlockedDescription: 'Inscrito para sempre na história da EEMTI Alfredo Machado como Lenda da Paz!',
    funnyQuote: '‘Os grandes feitos pela paz ecoam pela eternidade.’',
    funnySticker: '👑',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'divine_crown_flame',
    isUnlocked: false,
    xpReward: 50,
    currentProgress: 0,
    maxProgress: 35,
    progressUnit: 'insígnias',
    requirementHint: 'Alcance Nível 18+ com 2.500 XP e 35 conquistas.'
  },

  // 47 a 54: Conquistas Secretas (isSecret: true)
  {
    id: 'secret_detetive_sentinela',
    title: 'Chave de Esqueleto da Masmorra',
    subtitle: 'Investigação Profunda de Detetive',
    description: 'Investigou as leis, explorou os tipos de bullying, realizou quiz e triagem.',
    unlockedDescription: 'Desvendou todas as conexões secretas entre leis, agressões e mediação!',
    funnyQuote: '‘Elementar, meu caro Sentinela: o conhecimento abre qualquer masmorra.’',
    funnySticker: '🗝️',
    category: 'detetive',
    tier: 'prata',
    iconType: 'skeletron_key',
    isUnlocked: false,
    isSecret: true,
    xpReward: 50,
    secretRewardCosmeticId: 'badge_detetive_sentinela',
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'etapas',
    requirementHint: 'Explore as leis, estude 4 tipos de bullying e faça 1 quiz.'
  },
  {
    id: 'secret_combo_conhecimento',
    title: 'Selo do Cultista Lunático',
    subtitle: 'A Tríade Sagrada do Saber',
    description: 'Concluiu quizzes, módulo de respeito e a matriz de tipologias de forma coordenada.',
    unlockedDescription: 'Combinou respeito, estudo legal e triagem com perfeição arcana!',
    funnyQuote: '‘Tríade arcana do saber: Estudo, Respeito e Ação consciente.’',
    funnySticker: '⚡',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'cultist_sigil',
    isUnlocked: false,
    isSecret: true,
    xpReward: 75,
    secretRewardCosmeticId: 'icon_raio_sabedoria',
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'pilares',
    requirementHint: 'Combine 3 quizzes com o módulo de respeito e triagem.'
  },
  {
    id: 'secret_mente_atenta',
    title: 'Terceiro Olho Cósmico',
    subtitle: 'Foco Absoluto e Percepção Aguçada',
    description: 'Acumulou 25 respostas em quizzes com aproveitamento consistente e rápido.',
    unlockedDescription: 'Percepção aguçada e reflexos mentais que enxergam além do óbvio!',
    funnyQuote: '‘O terceiro olho nunca deixa passar uma oportunidade de pacificação.’',
    funnySticker: '👁️',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'third_eye_cosmic',
    isUnlocked: false,
    isSecret: true,
    xpReward: 75,
    secretRewardCosmeticId: 'effect_mente_atenta_aurora',
    currentProgress: 0,
    maxProgress: 25,
    progressUnit: 'questões',
    requirementHint: 'Responda a 25 questões com alto índice de acerto.'
  },
  {
    id: 'secret_codigo_secreto',
    title: 'Chave Criptografada das Sombras',
    subtitle: 'Decodificação da Paz Escolar',
    description: 'Explorou 6 tipos de bullying, 2 respirações 4-7-8 e frases de apoio.',
    unlockedDescription: 'Decodificou a chave mestre da harmonia e discrição escolar!',
    funnyQuote: '‘Código decodificado com sucesso: Escola protegida e acolhedora.’',
    funnySticker: '📟',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'coded_shadow_key',
    isUnlocked: false,
    isSecret: true,
    xpReward: 100,
    secretRewardCosmeticId: 'frame_codigo_secreto',
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'chaves',
    requirementHint: 'Estude 6 tipos de bullying, faça 2 respirações e veja as frases.'
  },
  {
    id: 'secret_sentinela_empatia',
    title: 'Coração Sagrado dos Mares',
    subtitle: 'Acolhimento Perolado',
    description: 'Finalizou o módulo de respeito, 6 escolhas empáticas e apoio emocional.',
    unlockedDescription: 'Coração perolado que ilumina e acolhe até nos dias mais difíceis.',
    funnyQuote: '‘Onde outros viram as costas, o sentinela estende a mão e o coração.’',
    funnySticker: '🌊',
    category: 'empatia',
    tier: 'ouro',
    iconType: 'ocean_heart_pearl',
    isUnlocked: false,
    isSecret: true,
    xpReward: 75,
    secretRewardCosmeticId: 'frame_aura_empatia_secreta',
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'marcos',
    requirementHint: 'Complete o módulo de respeito e pratique escolhas empáticas.'
  },
  {
    id: 'secret_precisao_absoluta',
    title: 'Rifle de Precisão com Mira Holográfica',
    subtitle: 'Maestria Total de Acertos',
    description: 'Gabaritou 2 quizzes com 100% e concluiu 3 triagens de semáforo com mira telescópica.',
    unlockedDescription: 'Pontaria ética e pedagógica perfeita: 100% de acertos!',
    funnyQuote: '‘A precisão na empatia é a maior de todas as virtudes.’',
    funnySticker: '🎯',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'sniper_crosshair',
    isUnlocked: false,
    isSecret: true,
    xpReward: 100,
    secretRewardCosmeticId: 'badge_precisao_absoluta',
    currentProgress: 0,
    maxProgress: 2,
    progressUnit: 'quizzes 100%',
    requirementHint: 'Gabarite 2 quizzes e realize triagens com perfeição.'
  },
  {
    id: 'secret_explorador_noturno_areas',
    title: 'Ilha Flutuante nas Alturas',
    subtitle: 'Mochileiro de Todos os Biomas',
    description: 'Interagiu com todas as 6 áreas principais da plataforma Sentinela Escolar.',
    unlockedDescription: 'Visitou Leis, Respeito, Tipos, Quiz, Respiração e SOS nas alturas!',
    funnyQuote: '‘Quem conhece cada bioma da escola sabe exatamente como protegê-la.’',
    funnySticker: '☁️',
    category: 'detetive',
    tier: 'prata',
    iconType: 'sky_island_biome',
    isUnlocked: false,
    isSecret: true,
    xpReward: 50,
    secretRewardCosmeticId: 'icon_bussola_astral',
    currentProgress: 0,
    maxProgress: 6,
    progressUnit: 'áreas',
    requirementHint: 'Visite todas as áreas pedagógicas e práticas do app.'
  },
  {
    id: 'secret_lenda_oculta',
    title: 'Olho Supremo do Lorde Lunar',
    subtitle: 'O Mistério Cósmico dos Corredores',
    description: 'Alcançou Nível 8+, 15+ conquistas, 4 quizzes e 5 triagens concluídas.',
    unlockedDescription: 'A lendária e mítica figura protetora da EEMTI Alfredo Machado!',
    funnyQuote: '‘Uma lenda oculta não precisa de holofotes para transformar o mundo.’',
    funnySticker: '🌙',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'moon_lord_cosmic_eye',
    isUnlocked: false,
    isSecret: true,
    xpReward: 200,
    secretRewardCosmeticId: 'title_lenda_oculta',
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'marcos',
    requirementHint: 'Alcance Nível 8+ com 15 conquistas e ampla exploração.'
  }
];
